spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    devtools:
      livereload:
        enabled: true
      restart:
        enabled: true
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/qna_service?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true